export enum ActionTypes {
  // auth
  SET_USER = 'auth/SET_USER',
  SET_INTEGRATION_COMPLETE_SUCCESS = 'auth/SET_INTEGRATION_COMPLETE_SUCCESS',

  // audienceStat
  SET_AUDIENCE_STATS = 'audienceStat/SET_AUDIENCE_STATS',
  SET_AUDIENCE_STATUS = 'audienceStat/SET_AUDIENCE_STATUS',
  CLEAR_AUDIENCE_STATS = 'audienceStat/CLEAR_AUDIENCE_STATS',

  // pageCrawls
  SET_RECENT_PAGE_CRAWLS = 'pageCrawls/SET_RECENT_PAGE_CRAWLS',
}
