export enum MutationTypes {
  // auth
  UPDATE_USER = 'UPDATE_USER',
  SET_IS_LOADING = 'SET_IS_LOADING',
  GO_TO_NEXT_SIGN_UP_STEP = 'GO_TO_NEXT_SIGN_UP_STEP',

  // audienceStat
  SET_AUDIENCE_STATS = 'SET_AUDIENCE_STATS',
  CLEAR_AUDIENCE_STATS = 'CLEAR_AUDIENCE_STATS',
  SET_LIVE_AUDIENCE_COUNT = 'SET_LIVE_AUDIENCE_COUNT',
  SET_AUDIENCE_TOTAL_REVENUE = 'SET_AUDIENCE_TOTAL_REVENUE',
  SET_AUDIENCE_STATUS = 'SET_AUDIENCE_STATUS',

  // pageCrawls
  SET_RECENT_PAGE_CRAWLS = 'SET_RECENT_PAGE_CRAWLS',
  SET_RECENT_PAGE_CRAWLS_IS_LOADING = 'SET_RECENT_PAGE_CRAWLS_IS_LOADING',

  MOBILE_BANNER_SHOWN = 'MOBILE_BANNER_SHOWN',
}
