export enum ActionTypes {
  // auth
  SET_USER = 'auth/SET_USER',
  SET_SIGNUP_INFO = 'auth/SET_SIGNUP_INFO',
  SIGN_OUT = 'auth/SIGN_OUT',

  // audiences
  SET_AUDIENCES = 'audiences/SET_AUDIENCES',
  SET_AUDIENCE_STATUS = 'audiences/SET_AUDIENCE_STATUS',
  SET_AUDIENCE_TTL = 'audiences/SET_AUDIENCE_TTL',
  SET_AUDIENCE_LOOKBACK = 'audiences/SET_AUDIENCE_LOOKBACK',
  SET_AUDIENCE_CONFIDENCE = 'audiences/SET_AUDIENCE_CONFIDENCE',
  SET_IS_AUDIENCE_SETTINGS_SAVING_NEEDED = 'audiences/SET_IS_AUDIENCE_SETTINGS_SAVING_NEEDED',
  SET_ARE_AUDIENCE_SETTINGS_UPDATED = 'audiences/SET_ARE_AUDIENCE_SETTINGS_UPDATED',

  // analytics
  SET_ANALYTICS = 'analytics/SET_ANALYTICS',
  SET_OVERLAP = 'analytics/SET_OVERLAP',
}
