export enum GetterTypes {
  // auth
  GET_AUTH = 'GET_AUTH',
  GET_USER_OBJECT = 'GET_USER_OBJECT',
  GET_SIGNUP_INFO = 'GET_SIGNUP_INFO',

  // audiences
  GET_AUDIENCES = 'GET_AUDIENCES',
  GET_AUDIENCES_IDS = 'GET_AUDIENCES_IDS',
  GET_LIVE_AUDIENCE_COUNT = 'GET_LIVE_AUDIENCE_COUNT',
  GET_IS_AUDIENCES_LOADED = 'GET_IS_AUDIENCES_LOADED',
  GET_IS_AUDIENCES_ERROR = 'GET_IS_AUDIENCES_ERROR',
  GET_AUDIENCE_BY_ID = 'GET_AUDIENCE_BY_ID',
  GET_AUDIENCE_STATUS = 'GET_AUDIENCE_STATUS',
  GET_AUDIENCE_TYPE = 'GET_AUDIENCE_TYPE',
  GET_AUDIENCE_TTL = 'GET_AUDIENCE_TTL',
  GET_AUDIENCE_LOOKBACK = 'GET_AUDIENCE_LOOKBACK',
  GET_AUDIENCE_CONFIDENCE = 'GET_AUDIENCE_CONFIDENCE',
  GET_AUDIENCE_NAME = 'GET_AUDIENCE_NAME',
  GET_AUDIENCE_OWNER = 'GET_AUDIENCE_OWNER',
  GET_AUDIENCE_PAUSED_BY_SELLERS = 'GET_AUDIENCE_PAUSED_BY_SELLERS',
  GET_IS_AUDIENCE_SETTINGS_UPDATED = 'GET_IS_AUDIENCE_SETTINGS_UPDATED',

  // analytics
  GET_SPEND_AND_IMPRESSIONS = 'GET_SPEND_AND_IMPRESSIONS',
  GET_SPEND_AND_IMPRESSIONS_BY_ID = 'GET_SPEND_AND_IMPRESSIONS_BY_ID',
  GET_TRAFFIC = 'GET_TRAFFIC',
  GET_OVERLAP = 'GET_OVERLAP',
  GET_IS_ANALYTICS_LOADED = 'GET_IS_ANALYTICS_LOADED',
  GET_IS_ANALYTICS_ERROR = 'GET_IS_ANALYTICS_ERROR',
  GET_AUDIENCES_TABLE_RAW_DATA = 'GET_AUDIENCES_TABLE_RAW_DATA',
}
