export enum MutationTypes {
  // auth
  SET_USER = 'SET_USER',
  SET_SIGNUP_INFO = 'SET_SIGNUP_INFO',
  SET_AUTH_ERROR = 'SET_AUTH_ERROR',

  // audiences
  SET_AUDIENCES = 'SET_AUDIENCES',
  SET_AUDIENCE_STATUS = 'SET_AUDIENCE_STATUS',
  SET_AUDIENCE_TTL = 'SET_AUDIENCE_TTL',
  SET_AUDIENCE_LOOKBACK = 'SET_AUDIENCE_LOOKBACK',
  SET_AUDIENCE_CONFIDENCE = 'SET_AUDIENCE_CONFIDENCE',
  SET_IS_AUDIENCE_SETTINGS_SAVING_NEEDED = 'SET_IS_AUDIENCE_SETTINGS_SAVING_NEEDED',
  SET_ARE_AUDIENCE_SETTINGS_UPDATED = 'SET_ARE_AUDIENCE_SETTINGS_UPDATED',

  // analytics
  SET_ANALYTICS = 'SET_ANALYTICS',
  SET_OVERLAP = 'SET_OVERLAP',
}
