export default [
  {
    day: {
      value: '2021-04-29',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 24,
    page_views: 53,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-06',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 15,
    page_views: 26,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-01',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 25,
    page_views: 48,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-09',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 35,
    page_views: 70,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-23',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 13,
    page_views: 26,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-13',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 21,
    page_views: 38,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-16',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 35,
    page_views: 69,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-07',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 25,
    page_views: 41,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-11',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 30,
    page_views: 53,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-15',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 32,
    page_views: 61,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-08',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 32,
    page_views: 68,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-10',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 23,
    page_views: 53,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-17',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 28,
    page_views: 60,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-19',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 27,
    page_views: 58,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-05',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 8,
    page_views: 16,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-12',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 32,
    page_views: 66,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-27',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 48,
    page_views: 76,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-03',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 40,
    page_views: 75,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-23',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 49,
    page_views: 86,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-28',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 42,
    page_views: 81,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-30',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 33,
    page_views: 68,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-14',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 35,
    page_views: 64,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-26',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 34,
    page_views: 74,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-02',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 22,
    page_views: 48,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-20',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 37,
    page_views: 67,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-18',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 17,
    page_views: 42,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-21',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 30,
    page_views: 63,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-22',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 25,
    page_views: 50,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-25',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 32,
    page_views: 62,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-24',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 40,
    page_views: 66,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-04',
    },
    audience_id: 'iab-243',
    audience_name: 'IAB 243',
    uniques: 22,
    page_views: 38,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-29',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 44,
    page_views: 73,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-06',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 35,
    page_views: 96,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-01',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 25,
    page_views: 48,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-09',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 35,
    page_views: 70,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-23',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 13,
    page_views: 26,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-13',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 21,
    page_views: 38,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-16',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 35,
    page_views: 69,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-07',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 25,
    page_views: 41,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-11',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 30,
    page_views: 53,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-15',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 32,
    page_views: 61,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-08',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 32,
    page_views: 68,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-10',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 23,
    page_views: 53,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-17',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 28,
    page_views: 60,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-19',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 27,
    page_views: 58,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-05',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 8,
    page_views: 16,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-12',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 32,
    page_views: 66,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-27',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 48,
    page_views: 76,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-03',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 40,
    page_views: 75,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-23',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 49,
    page_views: 86,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-28',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 42,
    page_views: 81,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-30',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 33,
    page_views: 68,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-14',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 35,
    page_views: 64,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-26',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 34,
    page_views: 74,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-02',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 22,
    page_views: 48,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-20',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 37,
    page_views: 67,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-18',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 17,
    page_views: 42,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-21',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 30,
    page_views: 63,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-22',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 25,
    page_views: 50,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-25',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 32,
    page_views: 62,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-04-24',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 40,
    page_views: 66,
    impressions: null,
    spend: null,
  },
  {
    day: {
      value: '2021-05-04',
    },
    audience_id: 'iab-555',
    audience_name: 'IAB 555',
    uniques: 22,
    page_views: 38,
    impressions: null,
    spend: null,
  },
];
